vault_nodes: # if you have serveral nodes (one of them is leader)
  # - "http://127.0.0.1:8200" 
  - "VAULT_NODE_1"
  - "VAULT_NODE_2"
  - "VAULT_NODE_2"

vault_token: "REPLACE_YOUR_VAULT_TOKEN"  # Replace with your minimal policy token
scrape_port: 8000
scrape_interval: 30
alert_threshold_minutes: 5
